[general]
live_config_reload = true

[env]

[window]
opacity = 0.9
decorations = "Full"
decorations_theme_variant = "Light"
dynamic_title = false

[window.padding]
x = 2
y = 2

[selection]
save_to_clipboard = false  # only copy when you explicitly RMB

# Right click: copy selection, then clear highlight
[[mouse.bindings]]
mouse = "Right"
mods  = "None"
action = "Copy"

[[mouse.bindings]]
mouse = "Right"
mods  = "None"
action = "ClearSelection"

[font]
size = 14
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style  = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style  = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style  = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style  = "Bold Italic"


[colors.primary]
background = "#002b36"
foreground = "#eee8d5"

[colors.normal]
black   = "#073642"
red     = "#dc322f"
green   = "#859900"
yellow  = "#b58900"
blue    = "#268bd2"
magenta = "#d33682"
cyan    = "#2aa198"
white   = "#eee8d5"

[colors.bright]
black   = "#002b36"
red     = "#cb4b16"
green   = "#586e75"
yellow  = "#657b83"
blue    = "#839496"
magenta = "#6c71c4"
cyan    = "#2aa198"
white   = "#fdf6e3"

[colors.selection]
text       = "#002b36"
background = "#eee8d5"
